[package]
name = "expense-report"
version = "0.1.0"
authors = ["Samuel Cox <crankydillo@gmail.com>"]

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
postgres = { version = "0.15", features = ["with-chrono"] }
chrono = { version = "0.4", features = ["serde"] }
